### ISSUE TITLE
Missing symfony/messenger component dependency

### ISSUE THREAD

**Issue by tristanbes** [Happyr/message-serializer#17]
It seem that message-serializer also need the messenger component but it's not required in the composer json;

So we get an error 
```
Error: During class fetch: Uncaught ReflectionException: Class Symfony\Comp
!!    onent\Messenger\Transport\Serialization\SerializerInterface not found in /U
!!    sers/me/workspace/myposeo-keyword-lambda/vendor/happyr/message-seri
!!    alizer/src/Serializer.php:15
```

**Comment by Nyholm** [comment]
It is only the `Serializer` that is dependent on Messenger. You could use the Transformers and Hydrators with any other type serializer. That is why we decided not to require symfony/messenger. We only do it in the tests.

**Comment by tristanbes** [comment]
okay :)
